openapi: 3.0.3
info:
  title: X-point API
  version: 1.0.0
  description: |
    **認証情報**<br>
    REST API の実行ではリクエストを X-point に送信する場合、ログイン ID による認証を必要とする方法、予め登録されたトークンコードを使用する方法の2種類があります。<br>
    接続に使用する情報は http ヘッダに指定する必要があります。<br>
    ヘッダに、認証情報、トークンコードいずれかの指定が無い REST API 実行は必ずエラー応答になります。<br><br>
    **トークン情報**`X-ATLED-Generic-API-Token`<br>
    ドメインコード、ユーザーコード、管理者サイト「フォーム管理」で生成したトークンコードを”:”で連結して、Base64 エンコードした情報を指定する。<br>
    <br>
    **認証情報**`Authorization`<br>
    OAuth2 認証のアクセストークンを指定する。
servers:
  - url: https://sub_domain.atledcloud.jp/xpoint
tags:
  - name: Private
paths:
  /multiapi/v1/forms:
    post:
      tags:
        - Private
      summary: フォーム新規登録
      description: |
        X-pointの画面でいうところの「フォーム管理>フォーム登録」の操作と、「フォーム管理>フォームグループ登録」をAPI提供する。<br>
        リクエストパラメータの project_category は対向システムがAgileWorksの場合は必須項目。<br>
        リクエストパラメータの form_group_id が省略された場合は、フォームグループの登録は行わない。<br>
        (グループ未所属になる)
      operationId: RegistForm
      requestBody:
        $ref: "#/components/requestBodies/PostFormInsertRequest"
      security:
        - bearerAuth: []
      responses:
        "200":
          $ref: "#/components/responses/PostFormInsertResponses200"
        "400":
          $ref: "#/components/responses/ErrorResponses400"

  # --------------------------------------------------------------------------------------------------

  /multiapi/v1/forms/{fid}:
    patch:
      tags:
        - Private
      summary: フォーム更新
      description: |
        X-pointの画面でいうところの「フォーム管理>修正>フォーム登録」の操作と、「フォーム管理>フォームグループ登録」をAPI提供する。<br>
        リクエストパラメータの project_category は対向システムがAgileWorksの場合は必須項目。<br>
        リクエストパラメータの form_group_id が省略された場合は、フォームグループの登録は行わない。<br>
        (現在のグループを維持する)
      operationId: UpdateForm
      requestBody:
        $ref: "#/components/requestBodies/PatchFormUpdateRequest"
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/path_fid_required"
      responses:
        "200":
          $ref: "#/components/responses/PatchFormUpdateResponses200"
        "400":
          $ref: "#/components/responses/ErrorResponses400"

  # --------------------------------------------------------------------------------------------------

  /api/v1/documents/preview:
    get:
      tags:
        - Private
      summary: フォームプレビュー
      description: |
        X-pointの画面でいうところの「フォーム管理」からプレビューする操作を行うURLをAPI提供する。<br>
        ※レスポンスのURLに遷移することでプレビュー画面を表示する。
      operationId: PreviewForm
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/query_fcd2"
        - $ref: "#/components/parameters/query_formname2"
      responses:
        "200":
          $ref: "#/components/responses/GetFormPreviewResponses200"
        "400":
          $ref: "#/components/responses/ErrorResponses400"

    # --------------------------------------------------------------------------------------------------

    post:
      tags:
        - Private
      summary: フォームプレビュー
      description: |
        TSFファイルを送信することで、フォームをプレビューするURLをAPI提供する。<br>
        ※レスポンスのURLに遷移することでプレビュー画面を表示する。<br>
        ※送信したTSFファイルは実際には登録されない。
      operationId: PreviewFormFromTsf
      requestBody:
        $ref: "#/components/requestBodies/PostFormPreviewRequest"
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/query_fcd2"
        - $ref: "#/components/parameters/query_formname2"
      responses:
        "200":
          $ref: "#/components/responses/PostFormPreviewResponses200"
        "400":
          $ref: "#/components/responses/ErrorResponses400"

    # --------------------------------------------------------------------------------------------------

  /api/v1/forms/{fid}/tsf:
    patch:
      tags:
        - Private
      summary: フォームダウンロード
      description: X-pointの画面でいうところの「フォーム管理>プロパティ」からTSFファイルをDLする操作と、同等の機能をAPI提供する。
      operationId: DownloadForm
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/path_fid2_required"
        - $ref: "#/components/parameters/query_version"
      responses:
        "200":
          $ref: "#/components/responses/PatchFormDownloadResponses200"
        "400":
          $ref: "#/components/responses/ErrorResponses400"
        "404":
          $ref: "#/components/responses/ErrorResponses404"

    # --------------------------------------------------------------------------------------------------

  /api/v1/forms/component:
    get:
      tags:
        - Private
      summary: コンポーネント一覧取得
      description: X-pointの画面でいうところの「フォーム管理>コンポーネント>各種コンポーネント」の操作と、同等の機能をAPI提供する。
      operationId: GetComponentList
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/query_type"
        - $ref: "#/components/parameters/query_limit2"
        - $ref: "#/components/parameters/query_offset4"
      responses:
        "200":
          $ref: "#/components/responses/GetComponentListResponses200"
        "400":
          $ref: "#/components/responses/ErrorResponses400"

# -----------------------------------------------
# コンポーネントの定義
# -----------------------------------------------

components:
  # -----------------------------------------------
  # セキュリティスキーマ components/securitySchemes
  # -----------------------------------------------

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: OAuth2 認証情報
    APIKeyAuth:
      type: apiKey
      in: header
      name: X-ATLED-Generic-API-Token
      description: トークン情報

  # -----------------------------------------------
  # パラメータ components/parameters
  # -----------------------------------------------

  parameters:
    path_fid_required:
      description: フォームID
      name: fid
      in: path
      schema:
        type: integer
        example: 999
      required: true

    query_fcd2:
      description: |
        フォームコード<br>
        ユニークなフォームコードを指定する必要あり
      name: fcd
      in: query
      schema:
        type: integer
        example: 999

    query_formname2:
      description: |
        フォーム名称<br>
        名称の完全一致で指定する必要あり
      name: formname
      in: query
      schema:
        type: string
        example: 経費申請書

    path_fid2_required:
      description: |
        ダウンロードするフォームID<br>
        数値で指定
      name: fid
      in: path
      schema:
        type: integer
        example: 999
      required: true

    query_version:
      description: |
        TSFファイルの版数<br>
        数値で指定<br>
        最新版の場合は省略する
      name: version
      in: query
      schema:
        type: integer
        example: 1

    query_type:
      description: |
        コンポーネント種別<br>
        masterWindow / autoNumber / stamp / resource<br>
        (一つだけ選択可)
      name: type
      in: query
      schema:
        type: string
        example: masterWindow

    query_limit2:
      description: |
        取得上限<br>
        コンポーネントを取得する件数の上限(デフォルト:50)<br>
        0を指定した場合は上限なし
      name: limit
      in: query
      schema:
        type: integer
        example: 0

    query_offset4:
      description: |
        オフセット値<br>
        件数のオフセット値(デフォルト:0)<br>
        上限なしの場合はオフセットもなし
      name: offset
      in: query
      schema:
        type: integer
        example: 0

    # -----------------------------------------------
    # リクエスト components/requestBodies
    # -----------------------------------------------

  requestBodies:
    PostFormInsertRequest:
      content:
        multipart/form-data:
          schema:
            required:
              - form_file
            type: object
            properties:
              form_file:
                description: tsfファイル
                type: string
                format: binary
              project_category:
                description: |
                  業務カテゴリ<br>
                  AgileWorks用パラメータ:AgileWorksのみ必須
                type: string
              form_group_id:
                description: |
                  所属するフォームグループID(複数可)<br>
                  X-point用パラメータ:数値の配列で指定
                type: array
                items:
                  example: []
              file_name:
                description: |
                  tsfファイル名称<br>
                  省略時はデフォルト名「formFile.tsf」となる
                type: string

    # --------------------------------------------------------------------------------------------------

    PatchFormUpdateRequest:
      content:
        multipart/form-data:
          schema:
            required:
              - form_file
            type: object
            properties:
              form_file:
                description: tsfファイル
                type: string
                format: binary
              project_category:
                description: |
                  業務カテゴリ<br>
                  AgileWorks用パラメータ:AgileWorksのみ必須
                type: string
              form_group_id:
                description: |
                  所属するフォームグループID(複数可)<br>
                  X-point用パラメータ:数値の配列で指定
                type: array
                items:
                  example: []
              file_name:
                description: |
                  tsfファイル名称<br>
                  省略時はデフォルト名「formFile.tsf」となる
                type: string

    # --------------------------------------------------------------------------------------------------

    PostFormPreviewRequest:
      content:
        multipart/form-data:
          schema:
            required:
              - form_file
            type: object
            properties:
              form_file:
                description: tsfファイル
                type: string
                format: binary

  # -----------------------------------------------
  # レスポンス components/responses
  # -----------------------------------------------

  responses:
    ErrorResponses400:
      description: "Error response"
      content:
        application/json:
          schema:
            type: object
            properties:
              error_code:
                type: integer
                example: 400
              error_message:
                type: string
                example: "{エラーメッセージ}"

    ErrorResponses401:
      description: "Error response"
      content:
        application/json:
          schema:
            type: object
            properties:
              error_code:
                type: integer
                example: 401
              error_message:
                type: string
                example: "{エラーメッセージ}"

    ErrorResponses403:
      description: "Error response"
      content:
        application/json:
          schema:
            type: object
            properties:
              error_code:
                type: integer
                example: 403
              error_message:
                type: string
                example: "{エラーメッセージ}"

    ErrorResponses404:
      description: "Error response"
      content:
        application/json:
          schema:
            type: object
            properties:
              error_code:
                type: integer
                example: 404
              error_message:
                type: string
                example: "{エラーメッセージ}"

    ErrorResponses500:
      description: "Error response"
      content:
        application/json:
          schema:
            type: object
            properties:
              error_code:
                type: integer
                example: 500
              error_message:
                type: string
                example: "{エラーメッセージ}"
              reasons:
                type: string
                example: ["{エラーメッセージ}"]

    ErrorResponses500_noReasons:
      description: "Error response"
      content:
        application/json:
          schema:
            type: object
            properties:
              error_code:
                type: integer
                example: 500
              error_message:
                type: string
                example: "{エラーメッセージ}"

    # --------------------------------------------------------------------------------------------------

    PostFormInsertResponses200:
      description: Successful response
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/PostFormInsertResponses200"
          examples:
            TSF登録完了:
              value:
                form_cd: form01
                form_id: 100
                form_group_id:
                  - 100
                  - 101
                  - 102
            TSF登録完了 メッセージあり:
              value:
                form_cd: form01
                form_id: 100
                form_group_id:
                  - 100
                  - 101
                  - 102
                warning:
                  - client_code で設定されているマスタ参照コンポーネント「顧客マスタ」の情報取得に失敗しました。\nフォーム作成後、コンポーネントが削除されたなどの可能性が考えられます。
            TSF登録失敗:
              value:
                warning:
                  - フォーム名称『経費申請書』は既に使われています。同じ名称ではフォームを作成できません。

    # --------------------------------------------------------------------------------------------------

    PatchFormUpdateResponses200:
      description: Successful response
      content:
        application/json:
          schema:
            type: object
            properties:
              form_cd:
                description: フォームCD
                type: string
                example: form01
              form_id:
                description: フォームID
                type: string
                example: 100
              form_group_id:
                description: |
                  所属フォームグループID<br>
                  数値の配列で指定
                example:
                  - 100
                  - 101
                  - 102

    # --------------------------------------------------------------------------------------------------

    GetFormPreviewResponses200:
      description: Successful response
      content:
        text/html: {}

    # --------------------------------------------------------------------------------------------------

    PostFormPreviewResponses200:
      description: Successful response
      content:
        text/html: {}

    # --------------------------------------------------------------------------------------------------

    PatchFormDownloadResponses200:
      description: Successful response
      content:
        application/octet-stream: {}

    # --------------------------------------------------------------------------------------------------

    GetComponentListResponses200:
      description: Successful response
      content:
        application/octet-stream:
          schema:
            type: object
            properties:
              master_window:
                description: |
                  マスタ参照コンポーネントウィンドウ<br>
                  コンポーネントオブジェクトのリスト
                type: array
                items:
                  allOf:
                    - $ref: "#/components/schemas/master_items"
                    - example:
                        - comid: 1
                          comname: 社員マスタ参照
                          column:
                            - id
                            - name
                            - age
                        - comid: 2
                          comname: 顧客マスタ参照
                          column:
                            - id
                            - name
                            - bank_name

  # -----------------------------------------------
  # スキーマ components/schemas
  # -----------------------------------------------

  schemas:
    PostFormInsertResponses200:
      type: object
      properties:
        form_cd:
          description: |
            フォームCD<br>
            正常時は必ず出力
          type: string
        form_id:
          description: |
            フォームID<br>
            正常時は必ず出力
          type: string
        form_group_id:
          description: |
            所属フォームグループID<br>
            正常時は必ず出力<br>
            数値の配列で指定
        warning:
          description: |
            メッセージ内容<br>
            文字列の配列で指定

    master_items:
      type: object
      properties:
        comid:
          description: コンポーネントID
          type: integer
        comname:
          description: コンポーネント名称
          type: string
        column:
          description: |
            列名<br> 
            文字列の配列で指定(マスタ参照ウィンドウコンポーネントのみ)
          type: array
          items:
            example: []
