# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: jekyll build
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.3" # Not needed with a .ruby-version file
          bundler-cache: true
      - name: build
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      # 変換したファイルをコミットしてプッシュ
      - name: Push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add ./_site/*
          git commit -m "HTML Commit." || echo "No changes to commit"
          git push origin main
